### ISSUE TITLE
repo size

### ISSUE THREAD

**Issue by neeasade** [iotek/urnn#6]
currently a fresh clone of this repo is ~10MB, and ~97% of that is from the `.git` folder. I'm thinking about doing another more aggressive run with [BFG repo cleaner](https://rtyley.github.io/bfg-repo-cleaner/), but that would mean anyone with this repo cloned would need to re-clone. leaving this issue open for any comments, else will do that in a few days.

**Comment by venam** [comment]
No problem from my side.
All the first commits were tests. I had no idea it would actually give some results.

You can go on with it.

**Comment by neeasade** [comment]
this turned out to be mostly from some lingering png files, post removing them, size is now 2.3mb.
