### ISSUE TITLE
Error reading "cascade_min_out_epochs"

### ISSUE THREAD

**Issue by asyncial** [iotek/urnn#9]
When I run `./urnn colors some_file.png`, I get the following error:
`FANN Error 4: Error reading "cascade_min_out_epochs" from configuration file "network/urnn.trained".
Segmentation fault (core dumped)
Use of uninitialized value $red in negation (-) at scripts/convert_val_to_xresources_colors_2.pl line 54, <stdin> line 1.
Use of uninitialized value $green in negation (-) at scripts/convert_val_to_xresources_colors_2.pl line 55, <stdin> line 1.
Use of uninitialized value $blue in negation (-) at scripts/convert_val_to_xresources_colors_2.pl line 56, <stdin> line 1.
*background: #7f7f7f
`
libpng and libfann are both installed.

**Comment by venam** [comment]
It seems like the network wasn't trained properly.
Have you initially ran `regen` and/or `retrain`?

**Comment by asyncial** [comment]
Ah yes, that was the problem, thank you very much!
